# Generated by Django 4.2.7 on 2023-12-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_users_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='users',
            name='sms_2FA',
        ),
    ]
