# Generated by Django 4.2.7 on 2024-01-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_users_validated_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ball_color',
            field=models.CharField(default='white', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='ball_speed',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='users',
            name='bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='player_1_color',
            field=models.CharField(default='white', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='player_2_color',
            field=models.CharField(default='white', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='walls',
            field=models.BooleanField(default=False),
        ),
    ]
