# Generated by Django 4.2.7 on 2024-01-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_users_ball_color_users_ball_speed_users_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='language',
            field=models.CharField(default='en', max_length=2, null=True),
        ),
    ]
