version: '3.8'

networks:
  transcendence:
    driver: bridge

volumes:
  nestjs:
    driver: local
    driver_opts:
      type: none
      device: ./nestjs
      o: bind
  angular:
    driver: local
    driver_opts:
      type: none
      device: ./angular
      o: bind

services:
  # postgres:
  #   container_name: postgres-dev
  #   restart: always
  #   image: postgres:16
  #   networks:
  #     - transcendence
  #   env_file:
  #     - .env

  nestjs:
    container_name: nestjs-dev
    restart: always
    build: ./nestjs
    networks:
      - transcendence
    # depends_on:
    #   - postgres
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - nestjs:/home/nestjs/app:delegated
    user: '1000:999'

  # angular:
  #   container_name: angular-dev
  #   restart: always
  #   build: ./angular
  #   networks:
  #     - transcendence
  #   depends_on:
  #     - nestjs
  #   env_file:
  #     - .env
  #   ports:
  #     - 80:80
  #   volumes:
  #     - angular:/home/
