version: '3.8'

networks:
  transcendence:
    driver: bridge

volumes:
  nestjs:
    driver: local
    driver_opts:
      type: none
      device: ./backend
      o: bind
  angular:
    driver: local
    driver_opts:
      type: none
      device: ./frontend
      o: bind

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:16
    networks:
      - transcendence
    env_file:
      - .env

  nestjs:
    container_name: nestjs
    restart: always
    build: ./backend
    networks:
      - transcendence
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - nestjs:/home/

  angular:
    container_name: angular
    restart: always
    build: ./frontend
    networks:
      - transcendence
    depends_on:
      - nestjs
    env_file:
      - .env
    ports:
      - 80:80
    volumes:
      - angular:/home/
