# Generated by Django 4.2.7 on 2023-11-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_remove_users_token_42_users_code_42'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='jwt',
            field=models.CharField(default=None, max_length=80, null=True),
        ),
    ]
