# Generated by Django 4.2.7 on 2023-11-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_users_jwt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jwt',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
