# Generated by Django 4.2.7 on 2023-12-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_users_jwt'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email_2FA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='qr_2FA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='sms_2FA',
            field=models.BooleanField(default=False),
        ),
    ]
