# Generated by Django 4.2.7 on 2024-01-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_remove_users_phone_remove_users_sms_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='validated_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
