# Generated by Django 4.2.7 on 2024-01-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_users_validated_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='walls',
            field=models.BooleanField(default=False),
        ),
    ]
