# Generated by Django 4.2.7 on 2024-01-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_alter_users_bonus_alter_users_walls'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='player_1_color',
            field=models.CharField(default='white', max_length=80),
        ),
        migrations.AddField(
            model_name='users',
            name='player_2_color',
            field=models.CharField(default='white', max_length=80),
        ),
    ]
