# Generated by Django 4.2.7 on 2024-01-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_alter_users_player_1_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ball_color',
            field=models.CharField(default='white', max_length=80, null=True),
        ),
    ]
