# Generated by Django 4.2.7 on 2024-01-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_users_ball_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ball_speed',
            field=models.IntegerField(default=3),
        ),
    ]
