name: Link PR to Trello

on:
  pull_request:
    branches: [ main ]
    types:
      - opened
      - synchronize
      - closed

jobs:
  link-pr-to-trello:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - uses: arikhativa/github-commit-to-trello-card@bbd1167a0fa7aadfb85fcd10bb2e1c15ec360779
        with:
          trello-api-key: ${{ secrets.TRELLO_KEY }}
          trello-auth-token: ${{ secrets.TRELLO_TOKEN }}
          trello-board-id: 6525a2be77477877cb027842
          trello-card-action: "Attachment"
          trello-list-name-pr-open: "To do"
          trello-list-name-commit: "Doing"
          trello-list-name-pr-closed: "Done"
          trello-card-id-pattern: "[a-zA-Z0-9]+"
         
