name: Link PR to Trello

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  link-pr-to-trello:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      

      - uses: jessicazu/trello-github-actions@v1.0
        with:
            trello-action: 'move_card_when_pull_request_opened'
    env:
      TRELLO_API_KEY: ${{ secrets.TRELLO_KEY }}
      TRELLO_API_TOKEN: ${{ secrets.TRELLO_TOKEN }}
      TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD }}
      TRELLO_LIST_ID: 6525a2bf96599ed962493cbc
      TRELLO_DEPARTURE_LIST_ID: 6525a2bf08c85ebb9867f09c
      TRELLO_DESTINATION_LIST_ID: 6525a2bf2acf714604dfc207
