name: Link PR to Trello 2

on:
  pull_request:
    branches: [ main ]
    # types:
    #   - opened
    #   - synchronize
    #   - closed

jobs:
  link-pr-to-trello2:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - uses: arikhativa/github-commit-to-trello-card@main
        with:
          trello-api-key: ${{ secrets.TRELLO_KEY }}
          trello-auth-token: ${{ secrets.TRELLO_TOKEN }}
          trello-board-id: 6525a2be77477877cb027842
          trello-card-action: "Attachment"
          trello-list-name-pr-open: "To do"
          trello-list-name-commit: "Doing"
          trello-list-name-pr-closed: "Done"
          trello-card-id-pattern: "[a-zA-Z0-9]+"
         
